- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0836adfedd0b81ee5 
    zone_id: Z0240592U12NCJ6BG5HL
    domain_name: aws45.fun #  above all required field to cfreate an ec2 usning ansible

    instance:
    - mongodb
    #- mysql

  tasks: 
  - name: create an ec2-instances
    amazon.aws.ec2_instance:        #module for to create ec2 #amazon spelling
     name: "{{ item }}"
     instance_type: t3.micro
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     tags:
       name: "{{ item }}"
    loop: "{{ instance }}"

    register: ec2_output #should not have blanks?

  - name: print ec2_output
    ansible.builtin.debug:
     msg: "{{ ec2_output}}"     

  - name: print public_ip_address
    ansible.builtin.debug: 
      msg: "{{ item.instance[0].public_ip_address }}"
     #when i am tring to access iteam(above line check) loop(below line) should be used
     #msg is for only printing
    loop: "{{ ec2_output.results}}"

  - name: print private_ip_address
    ansible.builtin.debug:
      msg: "{{ item.instance[0].private_ip_address }}"
     #when i am tring to access iteam(above line check) loop(below line) should be used
     #msg is for only printing
    loop: "{{ ec2_output.results}}"    


    


  